# Generated by Django 4.2.7 on 2026-04-11 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publish_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Publish at'),
        ),
        migrations.AddField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Published at'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('published', 'published'), ('scheduled', 'scheduled')], default='draft', max_length=20, verbose_name='Status'),
        ),
    ]
